title: Ubunchuu Trường Ú
email: https://tinyurl.com/yvs96rn2 
description: >- # this means to ignore newlines until "baseurl:"
  Nơi chứa tutorial về ubuntu mà bạn cần. Linux made easy!
url: "https://ubunchuu-truong-us.github.io"

# Minima date format
minima:
  date_format: "%b %-d, %Y"

  # Generate social links in footer
  social_links:
    - { platform: facebook, user_url: "https://www.facebook.com/ubunchuu.club.hcmus" }
    - { platform: github, user_url: "https://github.com/ubunchuu-truong-us" }

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
