[[main]]
  name = "Docs"
  url = "docs/giới-thiệu-về-linux"
  identifier = "docs"
  weight = 10

[[main]]
  name = "Linux Overview"
  url = "docs/giới-thiệu-về-linux"
  identifier = "linux-overview"
  weight = 11
  parent = "docs"

[[main]]
  name = "Linux Distributions"
  url = "docs/tìm-hiểu-chung-về-linux-distro"
  identifier = "linux-distributions"
  weight = 12
  parent = "docs"

[[main]]
  name = "Install Ubuntu (Clean Install)"
  url = "docs/cài-đặt-ubuntu-clean-install"
  identifier = "install-ubuntu-clean"
  weight = 13
  parent = "docs"

[[main]]
  name = "Install Ubuntu (Dual Boot)"
  url = "docs/cài-đặt-ubuntu-cho-người-dùng-song-song-với-windows"
  identifier = "install-ubuntu-dual-boot"
  weight = 14
  parent = "docs"

[[main]]
  name = "15 Days Fly With Tux"
  url = "docs/day-0-chào-mừng-đến-với-linux"
  identifier = "fly-with-tux"
  weight = 30

[[main]]
  name = "SQL Server"
  url = "https://github.com/ubunchuu-truong-us/sqlserver"
  identifier = "sqlserver"
  weight = 40
  [main.params]
    target = "_blank"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/ubunchuu-truong-us"
  weight = 10
